theme: minima
title: "My Projects"
author: "Burak Ayyorgun"
description: "This is my blog where I will be sharing my projects and passions. This blog has been created after I have done most of these projects, so some of the dates might not match."
